capetown <- read.csv("data/CapeTown_2020_October/listings.csv", stringsAsFactors = FALSE)
london <- read.csv("data/London_2020_October/listings.csv", stringsAsFactors = FALSE)
melbourne <- read.csv("data/Melbourne_2020_October/listings.csv", stringsAsFactors = FALSE)
mexico <- read.csv("data/MexicoCity_2020_October/listings.csv", stringsAsFactors = FALSE)
seattle <- read.csv("data/Seattle_2020_October/listings.csv", stringsAsFactors = FALSE)
tokyo <- read.csv("data/Tokyo_2020_October/listings.csv", stringsAsFactors = FALSE)